[tool.black]
line-length = 100

[tool.ruff]
lint.ignore = [
    "E501", # 行の長さが制限を超えた場合（長すぎる行）を無視
    ]
lint.select = [
    "C9",  # コーディング規約（例: PEP 8 に基づく規則）
    "E",   # エラー（一般的なPEP 8エラー）
    "F",   # Pyflakesのチェック（例: 未定義変数）
    "W",   # 警告（例: 不要な空白などの問題）
    "I",   # インポートの並び順に関するチェック
    "B",   # Bugbearのチェック（例: 潜在的なバグやコード臭）
    "N",   # 変数名や関数名の命名規則に関するチェック
    "T10", # Pytestに関連するチェック
    ]
line-length = 100
src = ["."]

[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "nicodb.settings"

[tool.dev-dependencies]
django-stubs = {extras = ["compatible-mypy"], version = "^1.12.0"}

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "nicodb.settings"
python_files = "tests.py test_*.py *_tests.py"
addopts = [
    "--cov=nicodb",
    "--cov=streamings",
    "--cov-fail-under=80",
    "--cov-report=term-missing",
    "--cov-report=html",
    ]
