# Generated by Django 5.1.5 on 2025-02-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="streaming",
            name="status",
            field=models.IntegerField(
                choices=[(10, "RESERVED"), (20, "ON_AIR"), (30, "ENDED")],
                verbose_name="配信ステータス",
            ),
        ),
    ]
