# Generated by Django 5.1.5 on 2025-02-14 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamings", "0002_alter_streaming_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("channel_id", models.BigIntegerField(unique=True, verbose_name="チャンネルID")),
                ("name", models.CharField(max_length=100, verbose_name="チャンネル名")),
                ("company_name", models.CharField(max_length=100, verbose_name="企業名")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
            ],
        ),
        migrations.AddField(
            model_name="streaming",
            name="channel",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="streamings.channel",
                verbose_name="チャンネルID",
            ),
            preserve_default=False,
        ),
    ]
