# Generated by Django 5.1.5 on 2025-02-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamings", "0003_channel_streaming_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="streaming",
            name="type",
            field=models.IntegerField(
                choices=[(10, "USER"), (20, "CHANNEL"), (30, "COMPANY")],
                default=10,
                verbose_name="配信タイプ",
            ),
            preserve_default=False,
        ),
    ]
